# Modified from: base16_default_dark
# Author: RayGervais <raygervais@hotmail.ca>

"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.virtual.ruler" = { bg = "base01" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base08"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "base0B"
"variable.other.member" = "base0A" # Changed cause by toml
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

# palette from GitHub chriskempson/base16-vim/colors/base16-tomorrow-night.vim
[palette]
base00 = "#1d1f21" # Default Background
base01 = "#282a2e" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#373b41" # Selection Background
base03 = "#969896" # Comments, Invisibles, Line Highlighting
base04 = "#b4b7b4" # Dark Foreground (Used for status bars)
base05 = "#c5c8c6" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e0e0e0" # Light Foreground (Not often used)
base07 = "#ffffff" # Light Background (Not often used)
base08 = "#cc6666" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#de935f" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f0c674" # Classes, Markup Bold, Search Text Background
base0B = "#b5bd68" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#8abeb7" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#81a2be" # Functions, Methods, Attribute IDs, Headings
base0E = "#b294bb" # Keywords, Storage, Selector, Markup Italic, Diff Changed                   # purple
base0F = "#a3685a" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
